name: Bug Report
description: Testing the form
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: "If you can see this, the file path and extension are correct!"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Enter your email.
    validations:
      required: true
